### ISSUE TITLE
cargo install bkmr problem

### ISSUE THREAD

**Issue by greglearns** [sysid/bkmr#5]
This project looks cool. I like that you can index local files.

```
rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
````

`cargo install bkmr` produces this linker error -- looks like a problem with openssl?

```
   Compiling bkmr v0.2.3
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcbbdj4J/symbols.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.0.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.1.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.10.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.11.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.12.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.13.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.14.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.15.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.2.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.3.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.4.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.5.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.6.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.7.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.8.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.bkmr.463d1482-cgu.9.rcgu.o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629.3uhifa41on32jkh4.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installISvYok/release/deps" "-L" "/home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib" "-L" "/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib" "-L" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installISvYok/release/deps/libbkmr-19b60beb8c78a2d3.rlib" "/tmp/cargo-installISvYok/release/deps/libopen-887aa8bdb59c6b7a.rlib" "/tmp/cargo-installISvYok/release/deps/libpathdiff-55704b400933d2a7.rlib" "/tmp/cargo-installISvYok/release/deps/libshellexpand-4af79510b1fdefdc.rlib" "/tmp/cargo-installISvYok/release/deps/libdirs-ba94768a55021832.rlib" "/tmp/cargo-installISvYok/release/deps/libdirs_sys-a932da168aecd01a.rlib" "/tmp/cargo-installISvYok/release/deps/libenv_logger-1b84330ab6a0b376.rlib" "/tmp/cargo-installISvYok/release/deps/libhumantime-eec0c664f4105c64.rlib" "/tmp/cargo-installISvYok/release/deps/libanyhow-143e6e8d5852e1da.rlib" "/tmp/cargo-installISvYok/release/deps/libdiesel_migrations-6c7cde8fa60a3663.rlib" "/tmp/cargo-installISvYok/release/deps/libmigrations_internals-b54f5f87638b90a6.rlib" "/tmp/cargo-installISvYok/release/deps/libtoml-4fcf998c91c08377.rlib" "/tmp/cargo-installISvYok/release/deps/libselect-9be3222a1c439ee5.rlib" "/tmp/cargo-installISvYok/release/deps/libbit_set-58b5cc6cb1150108.rlib" "/tmp/cargo-installISvYok/release/deps/libbit_vec-a6caa0994f6d36e7.rlib" "/tmp/cargo-installISvYok/release/deps/libmarkup5ever_rcdom-dd840d63a3638375.rlib" "/tmp/cargo-installISvYok/release/deps/libhtml5ever-ff374be7080e1318.rlib" "/tmp/cargo-installISvYok/release/deps/libmarkup5ever-937dae2d023865bd.rlib" "/tmp/cargo-installISvYok/release/deps/libstring_cache-047975f144ef6f09.rlib" "/tmp/cargo-installISvYok/release/deps/libprecomputed_hash-dfc606abb3101073.rlib" "/tmp/cargo-installISvYok/release/deps/libparking_lot-81ef746dc7f828fe.rlib" "/tmp/cargo-installISvYok/release/deps/libparking_lot_core-247c4bf10c65788f.rlib" "/tmp/cargo-installISvYok/release/deps/libsmallvec-cc96a7c44f83e3c4.rlib" "/tmp/cargo-installISvYok/release/deps/liblock_api-2bda17cccde1c198.rlib" "/tmp/cargo-installISvYok/release/deps/libphf-c31fc014f21e3cfb.rlib" "/tmp/cargo-installISvYok/release/deps/libphf_shared-70191db260c165d0.rlib" "/tmp/cargo-installISvYok/release/deps/libsiphasher-4ff44bf3863f33a5.rlib" "/tmp/cargo-installISvYok/release/deps/libtendril-5246e81094d09979.rlib" "/tmp/cargo-installISvYok/release/deps/libutf8-27dc294512ef37f0.rlib" "/tmp/cargo-installISvYok/release/deps/libfutf-890c4427ae4238b2.rlib" "/tmp/cargo-installISvYok/release/deps/libdebug_unreachable-27a448f89f154832.rlib" "/tmp/cargo-installISvYok/release/deps/libmac-4717ac86fe614fd2.rlib" "/tmp/cargo-installISvYok/release/deps/libreqwest-ff3b067d063b9bce.rlib" "/tmp/cargo-installISvYok/release/deps/libhyper_tls-7bedc223f4ab5f20.rlib" "/tmp/cargo-installISvYok/release/deps/libbase64-fa05a7d5fe01748f.rlib" "/tmp/cargo-installISvYok/release/deps/libipnet-cf308e175633a77d.rlib" "/tmp/cargo-installISvYok/release/deps/libtokio_native_tls-70d6c396eb03ac06.rlib" "/tmp/cargo-installISvYok/release/deps/libserde_urlencoded-36742e573e0d4db6.rlib" "/tmp/cargo-installISvYok/release/deps/libmime-eefcc3b53f1965e7.rlib" "/tmp/cargo-installISvYok/release/deps/libencoding_rs-abe8cf1c91abae6a.rlib" "/tmp/cargo-installISvYok/release/deps/libserde_json-8561d152f83a58d4.rlib" "/tmp/cargo-installISvYok/release/deps/libryu-e947d1969e34da9b.rlib" "/tmp/cargo-installISvYok/release/deps/libserde-485771e49f82216f.rlib" "/tmp/cargo-installISvYok/release/deps/libnative_tls-76f083c1874dcb90.rlib" "/tmp/cargo-installISvYok/release/deps/libopenssl_probe-3db319c990478c95.rlib" "/tmp/cargo-installISvYok/release/deps/libopenssl-22f8676cd403790b.rlib" "/tmp/cargo-installISvYok/release/deps/libforeign_types-65cb8192416760f5.rlib" "/tmp/cargo-installISvYok/release/deps/libforeign_types_shared-754222504d9b531a.rlib" "/tmp/cargo-installISvYok/release/deps/libopenssl_sys-52bb9347d5f8e4a6.rlib" "/tmp/cargo-installISvYok/release/deps/libhyper-9311c221c0d33fb8.rlib" "/tmp/cargo-installISvYok/release/deps/libwant-baa8ccf697b2dec6.rlib" "/tmp/cargo-installISvYok/release/deps/libtry_lock-751702e1a72b363e.rlib" "/tmp/cargo-installISvYok/release/deps/libhttparse-c2dfb4ab338e6eae.rlib" "/tmp/cargo-installISvYok/release/deps/libh2-7bd5460c47c6329a.rlib" "/tmp/cargo-installISvYok/release/deps/libindexmap-21a191a880524b98.rlib" "/tmp/cargo-installISvYok/release/deps/libhashbrown-9f0e9d018565ffe7.rlib" "/tmp/cargo-installISvYok/release/deps/libtokio_util-c0da212296804b14.rlib" "/tmp/cargo-installISvYok/release/deps/libtower_service-36f2830787d7bcd8.rlib" "/tmp/cargo-installISvYok/release/deps/libtracing-2a8324666628c583.rlib" "/tmp/cargo-installISvYok/release/deps/libtracing_core-a7d0466343c289b4.rlib" "/tmp/cargo-installISvYok/release/deps/libtokio-2dc7d26d3493821c.rlib" "/tmp/cargo-installISvYok/release/deps/libsocket2-b007f4ccead0991c.rlib" "/tmp/cargo-installISvYok/release/deps/libmio-d9aecb949aae474c.rlib" "/tmp/cargo-installISvYok/release/deps/libhttp_body-d13693893eb75ccb.rlib" "/tmp/cargo-installISvYok/release/deps/libfutures_util-ff0c8cad23cb06d3.rlib" "/tmp/cargo-installISvYok/release/deps/libfutures_io-f1f3fde0bc32945e.rlib" "/tmp/cargo-installISvYok/release/deps/libslab-dbbf615b4e519af7.rlib" "/tmp/cargo-installISvYok/release/deps/libfutures_channel-fba20277608f153a.rlib" "/tmp/cargo-installISvYok/release/deps/libpin_project_lite-1e15ebadec396d73.rlib" "/tmp/cargo-installISvYok/release/deps/libfutures_sink-0b1544cd604ccab5.rlib" "/tmp/cargo-installISvYok/release/deps/libfutures_task-9e9b8151bf544969.rlib" "/tmp/cargo-installISvYok/release/deps/libfutures_core-784c055060379b65.rlib" "/tmp/cargo-installISvYok/release/deps/liburl-d8b40e7ca209d665.rlib" "/tmp/cargo-installISvYok/release/deps/libidna-8a05b93aca0f7bba.rlib" "/tmp/cargo-installISvYok/release/deps/libunicode_normalization-1f8ff196dff9f604.rlib" "/tmp/cargo-installISvYok/release/deps/libtinyvec-861b92e789981b2d.rlib" "/tmp/cargo-installISvYok/release/deps/libtinyvec_macros-83e9da9a79a41697.rlib" "/tmp/cargo-installISvYok/release/deps/libunicode_bidi-368313958396c2ff.rlib" "/tmp/cargo-installISvYok/release/deps/libform_urlencoded-c53653dfe3f10dfa.rlib" "/tmp/cargo-installISvYok/release/deps/libpercent_encoding-63e5b3e5164990c2.rlib" "/tmp/cargo-installISvYok/release/deps/libhttp-5c4aaebc06293f92.rlib" "/tmp/cargo-installISvYok/release/deps/libitoa-eebfe3513fdd3a03.rlib" "/tmp/cargo-installISvYok/release/deps/libbytes-9ed62fcceabc25e4.rlib" "/tmp/cargo-installISvYok/release/deps/libfnv-35f9d07a182d9c70.rlib" "/tmp/cargo-installISvYok/release/deps/libskim-caf1352b9e1079ff.rlib" "/tmp/cargo-installISvYok/release/deps/libnix-0baef9f1a3ca3aa1.rlib" "/tmp/cargo-installISvYok/release/deps/libmemoffset-264ad73a6eabaae2.rlib" "/tmp/cargo-installISvYok/release/deps/libpin_utils-cb454c418ac94281.rlib" "/tmp/cargo-installISvYok/release/deps/libderive_builder-a44797fee1223052.rlib" "/tmp/cargo-installISvYok/release/deps/libtimer-3fba47bb049d069d.rlib" "/tmp/cargo-installISvYok/release/deps/librayon-50b1fe04051b8250.rlib" "/tmp/cargo-installISvYok/release/deps/librayon_core-0c6fd5808b1ef3c2.rlib" "/tmp/cargo-installISvYok/release/deps/libnum_cpus-a7af00b27487645b.rlib" "/tmp/cargo-installISvYok/release/deps/libeither-af60d4759ec51c5f.rlib" "/tmp/cargo-installISvYok/release/deps/libdefer_drop-2123b34225a37b4c.rlib" "/tmp/cargo-installISvYok/release/deps/libfuzzy_matcher-ff144561f8b275e0.rlib" "/tmp/cargo-installISvYok/release/deps/libthread_local-355bf93cc2e881c6.rlib" "/tmp/cargo-installISvYok/release/deps/libregex-56d377950559e8c8.rlib" "/tmp/cargo-installISvYok/release/deps/libaho_corasick-7c988a2f7359094a.rlib" "/tmp/cargo-installISvYok/release/deps/libmemchr-6ef6e242f488a2a9.rlib" "/tmp/cargo-installISvYok/release/deps/libregex_syntax-6d338df9e30e1c81.rlib" "/tmp/cargo-installISvYok/release/deps/libvte-8bb98ff5e59fe416.rlib" "/tmp/cargo-installISvYok/release/deps/libutf8parse-c6dbf3ff44dc1c03.rlib" "/tmp/cargo-installISvYok/release/deps/libarrayvec-192032437e2d3ea9.rlib" "/tmp/cargo-installISvYok/release/deps/libbeef-f1194956a324f73b.rlib" "/tmp/cargo-installISvYok/release/deps/libtuikit-a508627e32ce7d8f.rlib" "/tmp/cargo-installISvYok/release/deps/libterm-845b8c638678a129.rlib" "/tmp/cargo-installISvYok/release/deps/libdirs_next-3b683ce4e980f254.rlib" "/tmp/cargo-installISvYok/release/deps/libdirs_sys_next-79ac7906411834b6.rlib" "/tmp/cargo-installISvYok/release/deps/libnix-74a31ba8ad5f8fa9.rlib" "/tmp/cargo-installISvYok/release/deps/libcrossbeam-7839949865095435.rlib" "/tmp/cargo-installISvYok/release/deps/libcrossbeam_channel-198a523685fe7003.rlib" "/tmp/cargo-installISvYok/release/deps/libcrossbeam_deque-06fb0fc60cc91908.rlib" "/tmp/cargo-installISvYok/release/deps/libcrossbeam_queue-162182c287690acf.rlib" "/tmp/cargo-installISvYok/release/deps/libcrossbeam_epoch-09b54eb605b7ec6d.rlib" "/tmp/cargo-installISvYok/release/deps/libmemoffset-4c38a405616fa9d1.rlib" "/tmp/cargo-installISvYok/release/deps/libscopeguard-e7dd64e57ee55d88.rlib" "/tmp/cargo-installISvYok/release/deps/libcrossbeam_utils-0da19dc91d554e53.rlib" "/tmp/cargo-installISvYok/release/deps/liblazy_static-16eba8560d4e4203.rlib" "/tmp/cargo-installISvYok/release/deps/libstdext-309df11ad21caad5.rlib" "/tmp/cargo-installISvYok/release/deps/liblog-6f4d12daa1d17c8e.rlib" "/tmp/cargo-installISvYok/release/deps/libcfg_if-1ba8969e86818473.rlib" "/tmp/cargo-installISvYok/release/deps/libdiesel-d1619110c3436351.rlib" "/tmp/cargo-installISvYok/release/deps/libchrono-3c55daee8812e281.rlib" "/tmp/cargo-installISvYok/release/deps/libiana_time_zone-b1eff87fc01d8932.rlib" "/tmp/cargo-installISvYok/release/deps/libnum_integer-3c35fdb0b0316ff3.rlib" "/tmp/cargo-installISvYok/release/deps/libnum_traits-9f9dca71cf934f05.rlib" "/tmp/cargo-installISvYok/release/deps/libtime-346ff407c5ab8474.rlib" "/tmp/cargo-installISvYok/release/deps/liblibsqlite3_sys-64745dda5e25d01a.rlib" "/tmp/cargo-installISvYok/release/deps/libclap-9de5d52564f56846.rlib" "/tmp/cargo-installISvYok/release/deps/libunicode_width-bf8aed16c8d327b8.rlib" "/tmp/cargo-installISvYok/release/deps/libterminal_size-3519b3315f822cb4.rlib" "/tmp/cargo-installISvYok/release/deps/libstrsim-7c992f5a5a7d87e7.rlib" "/tmp/cargo-installISvYok/release/deps/libunicase-47add7e10f73f0e3.rlib" "/tmp/cargo-installISvYok/release/deps/libis_terminal-015cd08053ac5662.rlib" "/tmp/cargo-installISvYok/release/deps/librustix-ac45322dea682eaf.rlib" "/tmp/cargo-installISvYok/release/deps/liblinux_raw_sys-493879d8f8eef2e3.rlib" "/tmp/cargo-installISvYok/release/deps/libio_lifetimes-343480f5bb930621.rlib" "/tmp/cargo-installISvYok/release/deps/liblibc-d95dc0bcdf833f59.rlib" "/tmp/cargo-installISvYok/release/deps/libclap_lex-446dbf3b86332b7f.rlib" "/tmp/cargo-installISvYok/release/deps/libos_str_bytes-b5a77f179c459d8d.rlib" "/tmp/cargo-installISvYok/release/deps/libtermcolor-ae53359e3e764a60.rlib" "/tmp/cargo-installISvYok/release/deps/libbitflags-c7b073b268f2979c.rlib" "/tmp/cargo-installISvYok/release/deps/libonce_cell-7810cdc6f6965660.rlib" "/tmp/cargo-installISvYok/release/deps/libcamino-50672144e4f1c2cd.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c6192dd4c4d410ac.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ff7377081f1949cc.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-1cb453c5b22d87c0.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-ef80a3f609e31ec2.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-a690952b7d7394ed.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-33a38bd462dea42b.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-2804c2e5e3dadb10.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-6cea4a991902c072.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-3f9cac5a3a01ae1f.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-be29f577ccd2e0c7.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-40cbcc82de628eb3.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-ce9e735ebca3a756.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-52730b1d9cce8f6d.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-dbd9b472d3582c61.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-8f1d87098c577a9e.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-72ca4bc0b0597905.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-cdff4f89b0741001.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-92115cdd0b50e8be.rlib" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-7f2d6606c0ceff89.rlib" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/g123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installISvYok/release/deps/bkmr-076bce2fe4842629" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_setspecific@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `dlopen@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_rwlock_init@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `fstat64@GLIBC_2.33'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_rwlock_wrlock@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `dlerror@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `stat64@GLIBC_2.33'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_getspecific@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `pthread_create@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `pthread_mutexattr_settype@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `pthread_join@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `dlclose@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_rwlock_rdlock@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_key_delete@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `fstat@GLIBC_2.33'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `stat@GLIBC_2.33'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_once@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `dladdr@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_rwlock_destroy@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_key_create@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `pthread_rwlock_unlock@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.so: undefined reference to `dlsym@GLIBC_2.34'
          /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.40.1/lib/libsqlite3.so: undefined reference to `lstat64@GLIBC_2.33'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `bkmr` due to previous error
error: failed to compile `bkmr v0.2.3`, intermediate artifacts can be found at `/tmp/cargo-installISvYok`

```

**Comment by sysid** [comment]
@greglearns here I only can try to help indirectly since this does not seem to be a bkmr problem.

I am running and testing bkmr with sqlite version:  3.39.5 2022-10-14 20:58:05 554764a6e721fab307c63a4f98cd958c8428a5d9d8edfde951858d6fd02daapl. So this does seems to be ok.

You might need to provide set LD_LIBRARY_PATH for cc to find the sqlite libs. My setup here is: export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib".

**Comment by sysid** [comment]
Maybe this might also be helpful: https://github.com/sysid/bkmr/issues/6#issuecomment-1436010407

I pushed a new release with the rusqlite dependency included.

**Comment by greglearns** [comment]
2.4 solved the sqlite problem. The openssl problem still remains. I've found that relying on openssl causes a lot of problems on other people's systems, whereas if you use rustls, there are no problems. I see that you're using diesel, which uses openssl by default unless you select the rustls feature. That may solve the problem for not only me but lots of other people in the future.

**Comment by sysid** [comment]
Thank you @greglearns  for pointing this out. I am glad I could help. 

Would you mind providing the the correct cargo entry to activate the rustls feature?
